### ISSUE TITLE
Относительные пути в тесте прокруток

### ISSUE THREAD

**Issue by vladimir-nazarenko** [cscenter/project_screenshots#17]
Раньше в тестах прокруток путь к картинкам задавался относительно файла с тестом. https://github.com/cscenter/project_screenshots/pull/15 изменил это: теперь путь указан относительно директории запуска теста, что валит тесты в случае их запуска пачкой с помощью nosetests (а так тесты, вероятно, будут запускаться на билдботе, ну и я так тесты запускаю).

Нужно вернуть, как было, или откомментить, почему это ничего не ломает.

**Comment by sabrinamusatian** [comment]
мы поменяли путь запуска тестов и теперь просто пути в юнит тестах надо поправить или что?

**Comment by vladimir-nazarenko** [comment]
Путь запуска тестов не меняли, просто он был и может быть разным. А в тестах поменялся путь к картинкам, что жёстко фиксирует путь запуска тестов.

**Comment by vladimir-nazarenko** [comment]
Ой, прошу прощения, не вчитался :( Всё верно в пулл-реквесте.
